# This workflow ensures LICENSE-3rdparty.csv is up-to-date with all dependencies used

name: Check dependencies license

on: pull_request

permissions: {}

jobs:
  check-license-3rdparty:
    permissions:
      contents: read  # for actions/checkout to fetch code
    name: Check LICENSE-3rdparty.csv
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Check LICENSE-3rdparty.csv
        run: ./ci/check-license-3rdparty.sh
